#pragma once

// Weather-network uploaders are opt-in. A destination is not included in the
// firmware unless its build flag is explicitly set to 1.
#ifndef WEATHER_UPLOAD_WUNDERGROUND
#define WEATHER_UPLOAD_WUNDERGROUND 0
#endif
#ifndef WEATHER_UPLOAD_PWSWEATHER
#define WEATHER_UPLOAD_PWSWEATHER 0
#endif
#ifndef WEATHER_UPLOAD_CWOP
#define WEATHER_UPLOAD_CWOP 0
#endif
#ifndef WEATHER_UPLOAD_WEATHERCLOUD
#define WEATHER_UPLOAD_WEATHERCLOUD 0
#endif
#ifndef WEATHER_UPLOAD_WINDY
#define WEATHER_UPLOAD_WINDY 0
#endif
#ifndef WEATHER_UPLOAD_AWEKAS
#define WEATHER_UPLOAD_AWEKAS 0
#endif
#ifndef WEATHER_UPLOAD_WOW_BE
#define WEATHER_UPLOAD_WOW_BE 0
#endif

#if (WEATHER_UPLOAD_WUNDERGROUND != 0 && WEATHER_UPLOAD_WUNDERGROUND != 1) || \
    (WEATHER_UPLOAD_PWSWEATHER != 0 && WEATHER_UPLOAD_PWSWEATHER != 1) || \
    (WEATHER_UPLOAD_CWOP != 0 && WEATHER_UPLOAD_CWOP != 1) || \
    (WEATHER_UPLOAD_WEATHERCLOUD != 0 && WEATHER_UPLOAD_WEATHERCLOUD != 1) || \
    (WEATHER_UPLOAD_WINDY != 0 && WEATHER_UPLOAD_WINDY != 1) || \
    (WEATHER_UPLOAD_AWEKAS != 0 && WEATHER_UPLOAD_AWEKAS != 1) || \
    (WEATHER_UPLOAD_WOW_BE != 0 && WEATHER_UPLOAD_WOW_BE != 1)
#error "Every WEATHER_UPLOAD_* build flag must be 0 or 1"
#endif

#define WEATHER_UPLOAD_ANY \
    (WEATHER_UPLOAD_WUNDERGROUND || WEATHER_UPLOAD_PWSWEATHER || \
     WEATHER_UPLOAD_CWOP || WEATHER_UPLOAD_WEATHERCLOUD || \
     WEATHER_UPLOAD_WINDY || WEATHER_UPLOAD_AWEKAS || WEATHER_UPLOAD_WOW_BE)
